### PR TITLE
Add guides on use of unsafe functions from `Prelude`

### PR DESCRIPTION
**Pull request by pbrisbin**
This is a pattern I've been doing and I think it's useful. I'd like to
make it a team-wide guide.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Added a bunch of reviewers for visibility. I'll merge on a few approves, assuming no dissents.

**Review by z0isch — APPROVED** [review]
Never do anything unsafe and we don't need this!

**Review by joelmccracken — APPROVED** [review]

**Comment by joelmccracken** [comment]
alternative, perhaps worth bringing up: don't ever import them, but instead as a standard use pattern matching and `error`, which gives you a good spot to write _why_ its impossible/why the partial function is acceptable in this case. Thoughts? The best we can get in haskell for now is an informal proof of correctness etc.

**Comment by joelmccracken** [comment]
also, I do use partial functions in test on my personal stuff all the time; i think they're appropriate there. Downside is when it fails often the errors are bad, but it can make things so much easier/worth testing.

**Review by chris-martin — APPROVED** [review]

**Pull request merged**
