### PR TITLE
Document the use of the word fetch

### PR DESCRIPTION
**Pull request by eborden**
We almost consistently use the word fetch to describe retrieving data from the
database. It is worth standardizing around this idiom as it provides good
context clues for readers.

### CODE REVIEW

**Review by pbrisbin — APPROVED** [review]
But seriously, SGTM -- I love documenting naming like this.

(Not a big deal, but your examples don't kind-check.)

**Comment by eborden** [comment]
I'll kind check you! _shakes fist_

**Review by jdreaver — APPROVED** [review]

**Review by 5outh — APPROVED** [review]
Keep trying to make fetch happen!

**Review by cdparks — APPROVED** [review]
image

A delight to the senses

**Comment by eborden** [comment]
Okay, that looks like a majority vote :+1:

**Pull request merged**
